SELECT * FROM RESOURCE;
SELECT * FROM AVAILABILITY_PERIOD ORDER BY FROM_DATE DESC;
SELECT * FROM PRODUCTION_STATE_PERIOD ORDER BY FROM_DATE DESC;
SELECT * FROM CREW_PERIOD ORDER BY FROM_DATE DESC;
SELECT * FROM SHIFT_PERIOD ORDER BY FROM_DATE DESC;
SELECT * FROM PRODUCTION_RUN_PERIOD ORDER BY FROM_DATE DESC;
